[package]
name = "egui_test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
eframe = "0.27"
egui = "0.27"
egui_extras = "0.27"
env_logger = "0.11"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
