%%{init: {
  'gantt': {
    'fontSize': 16,
    'sectionFontSize': 18
  }
}}%%
gantt
    todayMarker off
    excludes weekends
    title Rust Notes App Development Timeline (Planned)
    dateFormat  DD.MM.YYYY
    section MS 1
    Project Sign-Off                  :          req,  02.06.2025, 03.06.2025
    Selecting Components              :         core,  02.06.2025, 04.06.2025
    Running First Tests               :         test,  03.06.2025, 05.06.2025
    section MS 2
    Define Note Struct                :         core,   04.06.2025, 05.06.2025
    Creating New Notes                :         data,   04.06.2025, 11.06.2025
    Save Encrypted Notes To File      :         data,   04.06.2025, 11.06.2025
    Note Encryption                   :         safety, 04.06.2025, 11.06.2025
    View Notes in Interface           :         ui,     10.06.2025, 12.06.2025
    Load Notes from File              :         data,   10.06.2025, 12.06.2025
    Deleting Notes                    :         data,   11.06.2025, 17.06.2025
    GUI Login Screen                  :         ui,     16.06.2025, 18.06.2025
    Add Password Hashing              :         data,   16.06.2025, 18.06.2025
    Password Verification             :         data,   16.06.2025, 18.06.2025
    Persist Login Across Sessions     :         ux,     18.06.2025, 19.06.2025
    section MS 3
    Improve Error Handling            :         ux,     23.06.2025, 26.06.2025
    Add Keyboard Shortcuts            :         ux,     23.06.2025, 24.06.2025
    Basic Settings Page               :         ui,     23.06.2025, 25.06.2025
    Style the GUI Layout              :         ui,     23.06.2025, 26.06.2025
    Write Usage Instructions          :         doc,    24.06.2025, 26.06.2025
    Export Note to Plain Text         :         ux,     24.06.2025, 25.06.2025
    Add Note Timestamps               :         ui,     24.06.2025, 25.06.2025
    Sort Notes by Timestamp           :         ui,     24.06.2025, 25.06.2025
    Package the App for Distribution  :         final,  25.06.2025, 26.06.2025
    Build and Test Windows Executable :         final,  25.06.2025, 26.06.2025
